# stickers.py
STICKERS = {
    "WELCOME_GENERAL": "CAACAgIAAxkBAAMjaOlm9yqPtZAzkUZ4sFJKRy_Z0vUAAnoXAAKplelI5DlqRcG3TJY2BA",
    "AFTER_NAME": "CAACAgQAAxkBAAMLaMQKbHA_ZS9mPWCX0Ksai1RVRXAAAk4TAAIhvbhQuv8wkfMmS9A2BA",
    "partner_left": "CAACAgQAAxkBAAMSaMQL4BJToUApDANpbk6UX2yNNrUAAgQZAAJSLfFQwx5oMII7EJ82BA",
    "barca_celebration": "CAACAgIAAxkBAAMRaMQLxNe1QnaHseNck3KPFV66EyAAAuFpAAIupUhKiRYvDhNYPRY2BA",
    "putin_politics": "CAACAgIAAxkBAAMTaMQMASLnGZ-jizhIVWL5-MnO5ZEAAmgbAAL736hI4OXTyCM3j7c2BA",
    "NABEEL_YOUNG": "CAACAgIAAxkBAAMFaMQJneOz5Ra59xj4ZHmMbi6Dma4AAkIaAAIlqulIFNFngJ-7yZg2BA",
    "registration_complete": "CAACAgQAAxkBAAMCaMQI4DqpxJjCicrNJTU3ZRhBDQMAAlcAAzb06QABOYOFe9k2ZKU2BA",
    "PUSH": "CAACAgIAAxkBAAMhaOlml18HIM2zSt_0VgmeyXCs-doAAncXAAJiZuhII4xbS4pXLxU2BA",
    "movies": "CAACAgIAAxkBAAMfaOlmlSYbq1M7MqPwAAGVcfLGiSHVAAL8FwAC6VD4Sz2C38vzBJk0NgQ",
    "wrong_usage": "CAACAgIAAxkBAAMdaOlmkgFfXft17EqVsO6mYNUKK5oAAoMTAAIgq9BKhqkKrOU_kYU2BA",
}

# convenience aliases (stiсker IDs)
WELCOME_STICKER = STICKERS["WELCOME_GENERAL"]
AFTER_NAME_STICKER = STICKERS["AFTER_NAME"]
PUSH_STICKER = STICKERS["PUSH"]
NABEEL_YOUNG_STICKER = STICKERS["NABEEL_YOUNG"]
